[package]
name = "serialport"
version = "0.1.2"
edition = "2024"

[dependencies.serde]
version = "1.0.219"
features = ["derive"]
optional = true

[target."cfg(windows)".dependencies.winapi]
version = "0.3.9"
features = ["cguid", "commapi", "handleapi", "setupapi", "winerror"]
